### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by henrikkoch** [lsolesen/billy-php-sdk#7]
Should it be possible to just place the two folders "src" and "tests" in the same folder on a web server and then from the "test" folder be able to execute etc. the "ClientTest.php" file? Or do I have to order the files in another way?

When trying this I get this: Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /volume1/web/billy/Billy/tests/ClientTest.php on line 14

I believe that you just put all the "src" files in a folder called Billy in the same folder at my own PHP files. But what i'm really asking for: Why does this repository then include a "src" and a "tests" folder? Shouldn't they be able to co-exist in the same folder, and from there be used with each other?

**Comment by lsolesen** [comment]
You need PHPUnit to run the tests. To run the tests you also need the
autoloader, see phpunit.xml

Den søn. 17. apr. 2016 12.27 skrev Henrik J. Koch <notifications@github.com

**Comment by henrikkoch** [comment]
Now I have put all the src files in a folder called Billy and prepared a php file which starts: (this file is in the same folder as where to folder called Billy are.

<?php
use Billy\Client\Request as Billy_Request;
use Billy\Client\Client as Billy_Client;

$api_key = '(my secret not shown here)';

try {
    $request = new Billy_Request($api_key);
    $client = new Billy_Client($request);
} catch (Exception $e) {
    //...
}

?>..
...

And now I get: 

..Fatal error: Class 'Billy\Client\Request' not found in ..

Can it be that my NAS's PHP does not support namespaces?

Any ideas why I get this error?

**Comment by lsolesen** [comment]
You need an autoloader, so your app knows where your files are located. If
you install the library using composer, you will get an autoloader for
free. Check out how to use composer.

Else you need to write your own PSR4 compliant autoloader.
Den 18/04/2016 23.04 skrev "Henrik J. Koch" <notifications@github.com>:

**Comment by lsolesen** [comment]
@henrikkoch Did you figure out how to use the autoloader from composer? Can I close this?

**Comment by henrikkoch** [comment]
No I didn't figure out how to install composer on my Synology NAS from where I run the PHP code

**Comment by lsolesen** [comment]
https://getcomposer.org/doc/00-intro.md
Den 22/04/2016 09.18 skrev "Henrik J. Koch" <notifications@github.com>:

**Comment by henrikkoch** [comment]
I think I managed to get composer to work on my NAS

I had to run composer update to make the vendor folder

My final testfile looked like the included. Does that look right?

[billytest_com.txt](https://github.com/lsolesen/billy-php-sdk/files/233579/billytest_com.txt)

**Comment by henrikkoch** [comment]
Where do you have a function to check if a contact is already there before making a new one with the same data?  Do I overlook something?

**Comment by lsolesen** [comment]
There is no dedicated function to check whether there is already a contact. You should probably keep track of that in your own app, like I do in the Drupal module (http://drupal.org/project/billysbilling). Or you can supply a pull request for that function.

**Comment by lsolesen** [comment]
I will close this now, as you got it to actually work.
